CC                 = g++
CFLAGS             = -o
PATH_HEADER_CPP    = main.cpp
PATH_HEADER_H      = socket.cpp
OUT                = server
OUT2               = client

all:
	${CC} ${CFLAGS} ${OUT} ${PATH_HEADER_CPP} ${PATH_HEADER_H}
